### ISSUE TITLE
Does not handle java opts with spaces

### ISSUE THREAD

**Issue by myoung34** [saltstack-formulas/elasticsearch-formula#43]
Fix to come when tested.

Setting 

```
elasticsearch:
    sysconfig:
      ES_STARTUP_SLEEP_TIME: 30
     ES_JAVA_OPTS: -Xms2g -Xmx2g
``` 

ends up as `ES_JAVA_OPTS=-Xms2g -Xmx2g` which is not valid in shell/sysconfig and causes a service start error:

```
[ec2-user@ip-10-0-3-52 ~]$ sudo service elasticsearch start
/etc/sysconfig/elasticsearch: line 4: -Xmx2g: command not found
```
